apiVersion: apps/v1
kind: Deployment
metadata:
  name:  health-insurance-app-deployment
  labels:
    app:  health-insurance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  health-insurance-app
  template:
    metadata:
      labels:
        app:  health-insurance-app
    spec:
      containers:
      - name: health-insurance-app-container
        image: gayatrihedau/myproject2:2
        ports:
        - containerPort: 8082
